export const TICKET_ACTION = {
	CREATE: "CREATE",
	READ: "READ",
	UPDATE: "UPDATE",
	DELETE: "DELEATE"
}
export const BROWSER_ACTION = {
	NEW_PAGE: "NEW_PAGE",
	PREVIOUS_PAGE: "PREVIOUS_PAGE",
	NEXT_PAGE: "NEXT_PAGE",
	UPDATE: "UPDATE"
}